hFig = figure(...
    'NumberTitle', 'off',...
    'Name', 'Example',...
    'Position', [680 558/2 500 500], ...
    'Color', 'white');
x = -2*pi:pi/16:2*pi;
y_cos = cos(x);
y_sin = sin(x);
hLineSize = line(...
    'XData', x,...
    'YData', y_sin,...
    'LineWidth', 3,... ...
    'Color', 'red');

