t = 0:pi/30:2*pi;
a = 1;
x = a * cos(t).^3;
y = a * sin(t).^3;

scrn = get(0, 'ScreenSize');
width = 420; height = 380;
figure('Color', [1 1 1],...
    MenuBar='none',...
    Name='Астроида', ...
    NumberTitle='off', ...
    Position=[fix((scrn(3)-width)/2), ...
    fix((scrn(4) - height) / 2) , width, height])
rectangle(Curvature=[1 1],...
    LineWidth=2.5,...
    LineStyle="-", ...
    Position=[-0.78 0.28 0.5 0.5])
line('Color', [0 0 1], ...
    'LineWidth', 2.5, ...
    'LineStyle', '-.', ...
    'Marker', 'o', ...
    'XData', x,...
    'YData', y)