st = struct('name', char('Ivan','Maria', 'SirGay'))
st.year = [2005; 2006; 2007]
[deblank(st.name(1,:)), ' - ', int2str(st.year(1))]
st.subjects = char("Math", "CS", "FL")
st.marks = randi([3, 5],3,3)
[deblank(st.name(1,:)), ' - ', int2str(st.year(1)), ' - "', int2str(st.marks(1,:)), '"']
length(st.marks(1,:))
sum(st.marks(1,:))
sum(st.marks(1,:))/length(st.marks(1,:))
[...
deblank(st.name(2,:)), ' - ', ...
int2str(st.year(2)), ' - "', ...
int2str(st.marks(2,:)), '" - ' ...
num2str(sum(st.marks(2,:))/length(st.marks(2,:)))
]

stud = struct(...
'name', 'Ivan',...
'year', 2005, ...
'marks', randi([3, 5], 1, 3), ...
'subject', ['Math'; 'CS'; 'FL'] ...
)

stud(3).name = 'SirGay'
stud(3).subject = char("Math", "CS", "FL")
stud(3)
